### ISSUE TITLE
nginx fails when jitsi_meet_server_name was changed

### ISSUE THREAD

**Issue by funkyfuture** [systemli/ansible-role-jitsi-meet#20]
changing `jitsi_meet_server_name` leads to the situation that there are two website configurations in `/etc/nginx/sites-enabled`. thus the `server_names_hash_bucket_size` directive is declared twice and `nginx` will fail to start.

this could either be fixed by allowing just one site configuration or by factoring that out to an extra configuration file. what would you prefer?

**Comment by 0x46616c6b** [comment]
We could change the `dest` in the template step.

```diff
  template:
-    dest: "/etc/nginx/sites-available/{{ jitsi_meet_server_name }}.conf"
+    dest: "/etc/nginx/sites-available/jitsi-meet.conf"
      src: nginx/sites-available/vhost.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx
```

**Comment by funkyfuture** [comment]
yep, if it's intended as single-site deployment.

actually i'm currently figuring out how to fix the `prosody` config as well.

**Comment by funkyfuture** [comment]
i'm not exactly sure what fixed the latter. i purged prosody and its config to redeploy. eventually the issue described in #11 was effective as well.

i'm probably providing a patch tomorrow.

**Comment by 0x46616c6b** [comment]
> i'm not exactly sure what fixed the latter. i purged prosody and its config to redeploy. eventually the issue described in #11 was effective as well.
> 
> i'm probably providing a patch tomorrow.

You need to delete the files under `/var/lib/prosody` when you purge your installation. Otherwise the old account data is in place and the role will not overwrite them. It is as you mentioned related to #11

**Comment by 0x46616c6b** [comment]
Hey, I would close this issue because the package from Jitsi Meet works with the server name as file name and it would be very complex to change this behaviour. What do you think? Maybe you can try to discuss this upstream with the maintainers of the debian package?

**Comment by funkyfuture** [comment]
i do agree. unfortunately there often too few time to contribute to upstream. maybe it'd make sense to collect a number of issues to make that more fruitful.
