### ISSUE TITLE
Package updates override custom web assets

### ISSUE THREAD

**Issue by funkyfuture** [systemli/ansible-role-jitsi-meet#24]
i observed that a custom watermark image was overwritten by a package update. also `debsums` complains about changed this and a changed `interface_config.js` and `title.html`. these are probably caused by a lack of facilitation on the upstream side. but maybe there is an elegant way around one or the other.

**Comment by 0x46616c6b** [comment]
We discussed this also in our deployment. It is possible to add the `interface_config.js` in another directory and link it correctly in the nginx configuration. For title I guess this is not possible.

**Comment by funkyfuture** [comment]
maybe it's too early, but i looked into it it and can't find a way to overcome the need to re-apply the role after a package upgrade.

would you be interested in a task that writes the affected files to `/etc/debsums-ignore`?

**Comment by t2d** [comment]
sure, just add it with a var that defaults to false like `jitsi_meet_debsums: false`

**Comment by funkyfuture** [comment]
done w/ 0faa6e7969259011cac9c9fd8677a69dd1d3dfb0
