### ISSUE TITLE
jitsi_meet_turn_secret

### ISSUE THREAD

**Issue by mateuszsocko** [systemli/ansible-role-jitsi-meet#56]
kipping: [node03] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [systemli.jitsi_meet : Set debconf options for jitsi-meet] **************************************************************************************************************
fatal: [node03]: FAILED! => {"msg": "'jitsi_meet_turn_secret' is undefined"}

PLAY RECAP *******************************************************************************************************************************************************************
node03                     : ok=30   changed=8    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0

**Comment by t2d** [comment]
as the error says, you have to define `jitsi_meet_turn_secret`

**Comment by mateuszsocko** [comment]
Nope propably i have.

Can you show me where? Maybe wrong file

**Comment by zrdimetc** [comment]
In 

`~/.ansible/roles/systemli.jitsi_meet/defaults/main.yml
`
add your "secret" strings for turn and videobridge and a muc "nickname".

```
# Jitsi-meet secrets
jitsi_meet_turn_secret: 'some-secret'
jitsi_meet_videobridge_secret: 'some-secret'
jitsi_meet_videobridge_muc_nickname: 'mucname'
```
